name: ssh to local

on:
  push:

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: attempting to ssh
        run: |
          sudo apt-get install sshpass
          sshpass -p chitra ssh supo@49.205.138.180
